# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9d7899341e53b48299972a98f2d9970098f4e57463fda05d91db673db43872d974146d93d52ea3d39d416c1de594277a7d3e7726f01da8531d8f4c27c31491fa

test:
  secret_key_base: 16043d47b47aa0a3194ee031e0781d03df061fdd9404d8f91292d9e315a95428b25691fbe1e732124c38d0a31ed46fae8809e90f99c73308840aa73f33c63be2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
